name: PromptTools

on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches:
      - steventkrawczyk-test

jobs:
  comment:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
     - name: Check out source repository
       uses: actions/checkout@v3
     - name: Set up Python ${{ matrix.python-version }}
       uses: actions/setup-python@v3
       with:
         python-version: ${{ matrix.python-version }}
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         python -m pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
     - name: Build prompttools
       run: |
         pip3 install .
     - name: Create markdown
       run: |
         DEBUG=1 python scripts/create_comment.py
     - name: Write comment
       uses: actions/github-script@v6
       with:
         script: |
           const fs = require('fs')
           fs.readFile('./markdown.md', 'utf8', (err, data) => {
             github.rest.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: data
             })
           });
